### ISSUE TITLE
CI other than Travis/deployment other than Heroku?

### ISSUE THREAD

**Issue by jdickey** [thekompanee/chamber#42]
We've been using CodeShip for our CI for quite some time now, and are extremely loath to switch out simply for a (very nice, admittedly) bit of security automation. How would we go about running our tests without uploading the secret keys? Or did my brain turn into a pumpkin at 0330 without me noticing? We're also planning on deploying to a non-Heroku server, so that's going to be an Issue as well&hellip;

**Comment by jfelchner** [comment]
@jdickey most CI solutions have a way to inject environment variables into their builds.

For example, CircleCI does this through their dashboard, Travis does this through the `travis.yml` file.  In the case of Circle, because it's never exposed to the repo, we can put `CHAMBER_KEY` with the value of our private `.chamber.pem` file.  You can do a similar thing with `travis.yml`.  In the case of `travis.yml`, you can use `travis secure` to encrypt it with the key that only travis knows about which makes it safe to commit.

I'm not sure how CodeShip works, but I'll assume they have a similar situation.

Same thing works transparently on any non-Heroku server.  If the environment has a `CHAMBER_KEY` environment variable that contains your private key, you're good to go.  If you want to use the "push" style like we have supported for Heroku, then I'll welcome a PR to add functionality for something other than Heroku. :grinning:

**Comment by jdickey** [comment]
Ah, I see; so environment-variable settings get picked up by Chamber and override whatever (encrypted-garbage-without-secret-key) values are specified in the Yaml file? ISTR reading that at some point; apologies for the pumpkinised lack of memory 10 hours ago. I'll go back and read the doc again; assuming you agree that my restated understanding is correct, kindly close the issue. Thanks! :+1:

**Comment by jfelchner** [comment]
@jdickey yes that's how it's *supposed* to work. 😉 If you have any issues, lemme know!

This behavior allows you to selectively choose which values (whether secured in the YAML or not) are specified in the environment. 

Like, for example, if I'm in production and I have:

```yaml
logging:
  server: # whatever
  level: info
  sql_statements: true
```

And I'm using those chamber values in my app, then on could theoretically (eg on Heroku):

```
heroku config:set LOGGING_LEVEL=debug
heroku restart
```

And voila, debug logging!

```
heroku config:unset LOGGING_LEVEL
heroku restart
```

And you're back to the value from the YAML (info in this case)

**Comment by zoras** [comment]
@jfelchner I am getting error while using `CHAMBER_KEY` ENV variables in Circle CI. 

> In the case of Circle, because it's never exposed to the repo, we can put `CHAMBER_KEY` with the value of our private `.chamber.pem` file. 

I used this in my local machine and works well

```[bash]
bash-3.2$ export CHAMBER_KEY="-----BEGIN RSA PRIVATE KEY-----
>...
> -----END RSA PRIVATE KEY-----"
`

But it errors out in Circle CI with the same https://circleci.com/bb/insuranceco/insurance/edit#env-vars saying
`OpenSSL::PKey::RSAError: Neither PUB key nor PRIV key:`

Anything I'm doing wrong?
