### ISSUE TITLE
Array as environment variable

### ISSUE THREAD

**Issue by jrmhaig** [thekompanee/chamber#51]
If I have an array in my configuration file like:

```yaml
array:
  - one
  - two
  - three
```

is there any way to override this as one or more environment variables? Eg,

```bash
export ARRAY_0=red
export ARRAY_1=blue
```

(This doesn't work - I've tried)

**Comment by jrmhaig** [comment]
I also tried;

```bash
export ARRAY="[ 'red', 'blue' ]"
```

as

```yaml
array: [ 'one', 'two', 'three' ]
```

is valid YAML format but this doesn't work either.

**Comment by jfelchner** [comment]
@jrmhaig have you tried `export ARRAY="red,blue"`?

**Comment by jrmhaig** [comment]
That sets the value to (literally) `red,blue`

**Comment by jfelchner** [comment]
I would say that this isn't going to work either but it's worth a shot.  My first thought is that chamber can't assume much about the state of an environment variable.

The most that I'm comfortable doing is boolean conversion.  Even something like "If it's all digits, convert to a number" is problematic because a string may just _happen_ to be all numbers.

**Comment by jfelchner** [comment]
I think that if something like that were to be added, I'd be open to adding `MY_ARRAY_1` where `1` is the index you'd like to replace or add.  And I believe the proper place for that would be: https://github.com/thekompanee/chamber/blob/master/lib/chamber/filters/environment_filter.rb

**Comment by jrmhaig** [comment]
Personally, I would expect the environment variables to replace the entire array rather than individual elements. Otherwise it may not be possible to remove unwanted elements.
Another question is what to do with missing indices, such as when `ARRAY_1` and `ARRAY_3` are set but not `ARRAY_2`. I would suggest that the number should give the order but not strictly the index so this would result in a two element array. I think that this is similar to how ordered lists in markdown works.

**Comment by jfelchner** [comment]
@jrmhaig I'd be ok with the "markdown style" behavior.

chamber doesn't currently look at "the current value from the YAML" of the key and then determine what to do if it finds an environment variable of that same key.  I think that would be an awesome feature, if potentially error-prone.

If you're up for a spike on it, I'd be open to the feature addition.

**Comment by jfelchner** [comment]
FWIW, I think that "potentially error-prone" is dependent on implementation.  I also think that if done right, it could be _much_ better than even the "boolean conversion" I'm doing.  Because it will be based on actual hard data rather than guessing.

**Comment by jrmhaig** [comment]
This is far from complete and possibly not the best implementation but is this what you mean?

https://github.com/jrmhaig/chamber/tree/maintain_type

While doing this I saw that `Show` converts an array to an environment variable as:

```
ANOTHER_LEVEL_LEVEL_THREE_AN_ARRAY="["item 1", "item 2", "item 3"]"
```

(See https://github.com/thekompanee/chamber/blob/master/spec/lib/chamber/commands/show_spec.rb#L22)
There are a couple of problems here:
1. The quotes are not escaped.
2. This is not how an array is represented in bash. Is it an array an another shell?

On the other hand, it does suggest that for consistency the correct way to represent an array should be on one line like:

```
ARRAY=("item 1" "item 2" "item 3")
```

**Comment by jfelchner** [comment]
@jrmhaig I'm digging that commit on your branch!

Regarding `show`, it's true that it's not technically "bashified".  Show is more for display only rather than "copy paste this somewhere".

I'm open to the idea of changing the `show` output to be the same format that we'd expect from an environment variable required to override a chamber setting in a YAML file.

Make sense?

**Comment by jfelchner** [comment]
Also FWIW, the output should _not_ be `ARRAY=("item 1" "item 2" "item 3")` while this is fine for copy-pasting, to make them portable, the environment variables need to only be strings.

**Comment by jrmhaig** [comment]
I have made a PR - #52 

I expect there to be a bit of discussion before merging as I have probably missed something in the internals of Chamber.

**Comment by jfelchner** [comment]
I decided to base the feature on what was discussed here, but got rid of any notion of "replacing a single item in the array" because there were too many edge cases that I didn't want to have to worry about.  There's too large of a surface area for potential bugs.

However...

What I came up with I think will be much better.  Namely that now, if the setting being overridden by an environment variable is an Array in the YAML document, the value of the environment variable will be parsed as YAML.  This means that an environment variable with the value:

```sh
export MY_CHAMBER_SETTING_ARRAY_VALUE="[ 'one', 'two', 'three' ]"
```

would override the value of:

```yaml
my_chamber_setting:
  array_value:
    - 'four'
    - 'five'
```

such that a call to:

```ruby
Chamber.env.my_chamber_setting.array_value
```

would yield:

```ruby
[
    'one',
    'two',
    'three',
]
```

This same behavior now also works for `Integer`s, `Boolean`s and `Float`s.  The old `BooleanConversionFilter` has been removed in favor of this more explicit conversion where the user has control over whether they want:

```sh
export MY_CHAMBER_SETTING_AMBIGUOUS_VALUE="true"
```

to be a `Boolean` or a `String`.

**Comment by jfelchner** [comment]
I also took the liberty of adding some additional functionality which will allow users to unset a value via the environment variables.

You can see the commit message [here](https://github.com/thekompanee/chamber/commit/ab66db79f265cb76c735ad59b86cc98dcf9dccaa)
