### ISSUE TITLE
chamber heroku compare fails with 'missing keyword :keys_only'

### ISSUE THREAD

**Issue by UsAndRufus** [thekompanee/chamber#76]
Current Behavior
--------------------------------------------------------------------------------
In the first scenario, I run the compare command get an error about `missing keyword :keys_only`. In the second scenario, I try running the command again with `--keys-only` and get an error saying `--keys-only` is not recognised. Either of these options should work

### Steps to Reproduce Scenario 1

  1. Run `chamber heroku compare --app=APP_NAME --api-token=API_TOKEN`
  2. Receive error `chamber/commands/comparable.rb:8:in `initialize': missing keyword: :keys_only (ArgumentError)`

### Screenshot

<img width="1511" alt="Screenshot 2022-05-19 at 17 58 45" src="https://user-images.githubusercontent.com/4115329/169356430-9c01f0c0-88df-4f10-a979-c56b9f4e063e.png">

### Steps to Reproduce Scenario 2

  1. Run `chamber heroku compare --app=APP_NAME --api-token=API_TOKEN --keys-only`
  2. Receive error:
 ```
ERROR: "chamber heroku compare" was called with arguments ["--keys-only"]
Usage: "chamber heroku compare"
 ```

### Screenshot

<img width="1434" alt="Screenshot 2022-05-19 at 18 02 46" src="https://user-images.githubusercontent.com/4115329/169357136-6e7a086c-59de-4931-95f4-534efe7932ee.png">

Expected Behavior
--------------------------------------------------------------------------------
Should be able to see the diff

Environment
--------------------------------------------------------------------------------

  * Device: 2021 MacBook Pro
  * OS: macOS
  * OS Version: Monterey
  * Running Ruby via asdf
  * Other commands with Chamber CLI works
  * Heroku CLI works

**Comment by jfelchner** [comment]
@UsAndRufus I'll be the first to admit the Heroku command has not gotten much love lately.  This is because, if you set the `CHAMBER_KEY` environment variable, you can just deploy your chamber settings themselves with the code and there's no need to set Heroku's environment variables.  Obviously this is not 100% accurate if you want chamber to be able to set something like `DATABASE_URL` but since I added the ability to upload the keys, I haven't needed any of the other Heroku commands.

That said, this should either work, or be removed.  There's no tolerance for a command that doesn't work so I'll look at this the next time I sit down to work on chamber.  Thank you for bringing it to my attention.

**Comment by jfelchner** [comment]
@UsAndRufus I did indeed decide to remove the integrations with cloud services.  This was little used.  I _did_ add a [full wiki page](https://github.com/thekompanee/chamber/wiki/Loading-Keys-From-Environment-Variables) on sending your keys to cloud services and also added a [note](https://github.com/thekompanee/chamber/wiki/Upgrading-To-Chamber-3.0#removal-of-cloud-settings-integrations) to the upgrade wiki page on my rationale for the removal.  If you have any issues with getting this working, please open an issue or a discussion!  Thank you for your patience!
